name: CI

on:
  pull_request:
  push:
    branches: [master, develop]

jobs:
  build:

    runs-on: ubuntu-latest

    # Use our own image with opam dependencies pre-installed to speed
    # things up.
    container: returntocorp/ocaml:ubuntu

    steps:
    - name: Pre-checkout fixes
      run: |
        sudo chmod -R 777 /github
        github_cache_dir="/__w"
        sudo mkdir -p "$github_cache_dir"
        sudo chmod -R 777 "$github_cache_dir"
    - uses: actions/checkout@v2

    # Move /home/user/.opam to the new HOME imposed by GHA
    - name: Post-checkout fixes
      run: ./.github/post-checkout

    - name: Install System Deps
      run: sudo apt update && sudo apt-get install -y --no-install-recommends wget swi-prolog mercurial
    - name: debugging
      run: |
        set -x
        echo "$HOME"
        echo "$PATH"
        opam exec -- ocamlc -v
        opam --version
        opam switch list
        opam switch
        pwd
        ls -a
    - name: Install pfff
      run: opam install -y .
    - name: Run Tests
      run: eval $(opam env); dune build && dune runtest -f
